In [1]:
from psst.matpower import read_matpower

In [2]:
mpc = read_matpower('./../cases/case5.m')

In [3]:
mpc.gen

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
0,1,40.00,0,30.0,-30.0,1,100,1,40,0,...,0,0,0,0,0,0,0,0,0,0
1,1,170.00,0,127.5,-127.5,1,100,1,170,0,...,0,0,0,0,0,0,0,0,0,0
2,3,323.49,0,390.0,-390.0,1,100,1,520,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0.00,0,150.0,-150.0,1,100,1,200,0,...,0,0,0,0,0,0,0,0,0,0
4,5,466.51,0,450.0,-450.0,1,100,1,600,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
mpc.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1,2,0.00281,0.0281,0.00712,400,400,400,0,0,1,-360,360
1,1,4,0.00304,0.0304,0.00658,0,0,0,0,0,1,-360,360
2,1,5,0.00064,0.0064,0.03126,0,0,0,0,0,1,-360,360
3,2,3,0.00108,0.0108,0.01852,0,0,0,0,0,1,-360,360
4,3,4,0.00297,0.0297,0.00674,0,0,0,0,0,1,-360,360
5,4,5,0.00297,0.0297,0.00674,240,240,240,0,0,1,-360,360

In [5]:
mpc.bus

   BUS_I  TYPE   PD      QD  GS  BS  AREA  VM  VA  BASEKV  ZONE  VMAX  VMIN
0      1     2    0    0.00   0   0     1   1   0     230     1   1.1   0.9
1      2     1  300   98.61   0   0     1   1   0     230     1   1.1   0.9
2      3     2  300   98.61   0   0     1   1   0     230     1   1.1   0.9
3      4     3  400  131.47   0   0     1   1   0     230     1   1.1   0.9
4      5     2    0    0.00   0   0     1   1   0     230     1   1.1   0.9

In [6]:
mpc.branch

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
0,1,2,0.00281,0.0281,0.00712,400,400,400,0,0,1,-360,360
1,1,4,0.00304,0.0304,0.00658,0,0,0,0,0,1,-360,360
2,1,5,0.00064,0.0064,0.03126,0,0,0,0,0,1,-360,360
3,2,3,0.00108,0.0108,0.01852,0,0,0,0,0,1,-360,360
4,3,4,0.00297,0.0297,0.00674,0,0,0,0,0,1,-360,360
5,4,5,0.00297,0.0297,0.00674,240,240,240,0,0,1,-360,360